### PR TITLE
Fix bug hiding aux variables (issue #43)

### PR DESCRIPTION
**Pull request by LukeJones123**
### Pull Request Checklist:
- [X ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes issue #43
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [ ] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 
Bug fix

* **Does this PR introduce a breaking change?:** 

* **Other information:**

### CODE REVIEW

**Comment by agstephens** [comment]
Hi @LukeJones123, this PR looks good. Thanks for spotting this bug. Could you please add a unit test, or modify an existing one, to verify that the aux variables are being correctly accessed. Then I will merge the PR.

**Comment by LukeJones123** [comment]
Hi Ag. I added a test to test_na_file.py. Running that revealed another bug actually, in getAuxVariable(), which I've also now fixed as part of this branch.

**Comment by agstephens** [comment]
Hi @LukeJones123, tests are now passing which is great.
Please can you update the `HISTORY.rst` file to note this change, and feel free to add yourself as an author to the `AUTHORS.md` (unless you'd rather remain anonymous - which is also fine :-)

**Comment by LukeJones123** [comment]
And do you want me to add a comment for the units-parsing feature branch too?

**Comment by agstephens** [comment]
Hi @LukeJones123, yes please.

**Comment by agstephens** [comment]
@LukeJones123, in the `HISTORY.rst` file, please add a section with the title:
`v2.0.2 (pending release)` - and I'll create a new release when the current set of updates/fixes are merged. Thanks

**Comment by LukeJones123** [comment]
Hi Ag. I've done that now.

**Comment by agstephens** [comment]
Thanks @LukeJones123

**Pull request merged**
